import 'package:quizpicableme/questions.dart';

final Map<String, Map<String, dynamic>> genre = {
  'gk': {
    'questions': <Question>[
      Question('When is the International Yoga Day celebrated ?', 'March 18',
          'June 21', 'July 21', 'December 23', 'June 21'),
      Question(
          'Which among the following cities in India, is not located in Golden Quadrilateral Road Network?',
          'Kolkata',
          'Delhi',
          'Mumbai',
          'Chandigarh',
          'Chandigarh'),
      Question(
          'Prime Minister Narendra Modi launched Swachha Bharat Mission officially on -',
          'Republic day',
          'Independence Day',
          'Gandhi Jayanti',
          'Environment Day',
          'Gandhi Jayanti'),
      Question(
          'Kyoto Protocol is related to',
          'Climate Change',
          'Air Pollution',
          'Greenhouse Gas',
          'Water Pollution',
          'Climate Change'),
      Question('Ozone Layer Preservation Day is celebrated on -',
          '16 September', '5 May', '5 June', '21 June', '16 September'),
      Question('The World Population Day is observed on ', 'June 11', 'May 11',
          'July 11', 'August 11', 'July 11'),
      Question('When is World Children’s Day observed?', 'November 14',
          'November 20', 'November 16', 'November 12', 'November 20'),
      Question(
          'Which of the following is not among 7 Wonders of the World',
          'Taj Mahal',
          'Colosseum',
          'Notre Dame',
          'The Great Wall of China',
          'Notre Dame'),
      Question(
          'The tropic of cancer does not pass through which of these Indian states ?',
          'Odisha',
          'West Bengal',
          'Madhya Pradesh',
          'Rajasthan',
          'Odisha'),
      Question(
          'Union Budget is always presented first in',
          'Joint Session of Parliament',
          'Rajya Sabha',
          'Lok Sabha',
          'Union Cabinet',
          'Rajya Sabha')
    ],
  },
  'sport': {
    'questions': <Question>[
      Question(
          'Which of the following awards is given for excellence in sports coaching in India?',
          'Arjuna Award',
          'Dhronacharya Award',
          'Dhyan Chand Award',
          'Rajiv Gandhi Khel Ratna',
          'Dhronacharya Award'),
      Question('When is national sports day of India celebrated?', 'August 29',
          'October 7', 'November 27', 'March 11', 'August 29'),
      Question('Lionel Messi is a player of which country?', 'Brazil',
          'Argentina', 'Germany', 'Italy', 'Argentina'),
      Question('The Ancient Olympics took place in honour of which Greek God?',
          'Apollo', 'Athena', 'Zeus', 'Hercules', 'Zeus'),
      Question(
          'Who was the first Indian to win an individual medal in Olympics?',
          'Karnam Malleshwari',
          'K. D. Jadhav',
          'Milkha Singh',
          'P. T. Usha',
          'K. D. Jadhav'),
      Question(' Where was the first World Cup Football held?', 'Brazil',
          'Canada', 'France', 'Uruguay', 'Uruguay'),
      Question(
          'Which of the following is the highest award in sports in the world?',
          'Arjuna Award',
          'Olympic Order',
          'Dronacharya Award',
          'Jesse Owens Award',
          'Olympic Order'),
      Question('In which category did India win its first Commonwealth medal?',
          'Hockey', 'Wrestling', 'Shooting', 'Athletics', 'Wrestling'),
      Question(' Which of the following is related to ICC trophy?', 'Hockey',
          'Lawn Tennis', 'Chess', 'Cricket', 'Cricket'),
      Question(
          ' ____________ has won Cricket world cup for the maximum number of times.',
          'India',
          'Sri Lanka',
          'Australia',
          'England',
          'Australia')
    ],
  },
  'entertainment': {
    'questions': <Question>[
      Question(
          'Who became the youngest artist in the history of Grammys to score six Gammy Award nominations?',
          'Billie Ellish',
          'Ariana Grande',
          'Swa lee',
          'Harry Styles',
          'Billie Ellish'),
      Question('Aishwarya Rai was crowned Miss World in which year?', '1992',
          '1993', '1994', '1995', '1994'),
      Question(
          'Which TV series won the Emmy award Outstanding Drama Series?',
          'House of Cards',
          'Game of Thrones',
          'Homeland',
          'The Americans',
          'Game of Thrones'),
      Question(
          'Who was named Top Touring Artist at the Billboard music awards?',
          'Taylor Swift',
          "Madonna",
          'Justin Bieber',
          'Bruno Mars',
          'Taylor Swift'),
      Question(
          'Which Adele song broke a YouTube record by receiving a billion views in 87 days?',
          'When We  Were Young',
          'I Miss You',
          'Remedy',
          'Hello',
          'Hello'),
      Question(
          'Which Disney movie was the highest-grossing film of 2016?',
          'The Jungle Book',
          'Captain America:Civil War',
          'Zootopia',
          'Finding Dory',
          'Captain America:Civil War'),
      Question('When was the boyband One Direction formed', 'May 11',
          'November 23', 'July 23', 'March 15', 'July 23'),
      Question('Filmfare awards started from the year', '1950', '1954', '1960',
          '1964', '1954'),
      Question('Which is not a Pixar movie?', 'Shrek', 'Toy Story',
          'Finding Nemo', 'Monsters Inc.', 'Shrek'),
      Question('Which book is NOT a title of a book in the Twilight series?',
          'New Moon', 'Breaking Dawn', 'Midnight', 'Eclipse', 'Midnight')
    ],
  },
  'socialmedia': {
    'questions': <Question>[
      Question('@-<--   What is this?', 'At my house', 'Asshole',
          'Where you at', 'Rose', 'Rose'),
      Question(
          'What does drip mean',
          'Has really cool clothes',
          'worked hard at gym',
          'related to alcohol',
          'Dont run into problems',
          'Has really cool clothes'),
      Question('Lowkey means', 'On down low', 'Kinda', 'Never',
          'At a low height', 'Kinda'),
      Question('What is the most popular day for tweets?', 'Tuesday', 'Friday',
          'Saturday', 'Thursday', 'Tuesday'),
      Question(
          'What is YouTube\'s slogan',
          'Think Different',
          'Broadcast Yourself',
          'Just Video it',
          'Watch whatever, whenever',
          'Broadcast Yourself'),
      Question(
          'A euphemism for hooking up is?',
          'Amazon and party',
          'Tinder and date',
          'Netflix and Chill',
          'Hulu  and hoop',
          'Netflix and Chill'),
      Question(
          'Who is Mark Zuckerberg',
          'Founder of Twitter',
          'Founder of My Space',
          'Founder of Facebook',
          'Founder of Google',
          'Founder of Facebook'),
      Question('In what year was Facebook launched', '2002', '2003', '2004',
          '2005', '2004'),
      Question(
          'What does pooshaw mean',
          'Go away',
          'I don\'t care what you have to say',
          'I gotta poo fast',
          'I have a question',
          'I don\'t care what you have to say'),
      Question(
          'If you say something controversial and don\'t care about anyone\'s response, you might say?',
          'Look the other way',
          'Bye,Felicia',
          'Sorry not sorry',
          'Don\'t at me',
          'Don\'t at me')
    ],
  },
  'friends': {
    'questions': <Question>[
      Question(
          'According to Ross in The One With The Cop, how many times did he and Rachel do it?',
          '249',
          '192',
          '298',
          '278',
          '298'),
      Question(
          'In the first ever episode Rachel ran away from her wedding to Barry. What was Barry\'s surname?',
          'Farber',
          'Felcher',
          'Former',
          'Filcher',
          'Farber'),
      Question('What magazine was sent to Miss Chanandler Bong?', 'Time',
          'Good House Keeping', 'TV Guide', 'Playboy', 'TV Guide'),
      Question('Who did Joey act as a butt double for?', 'Robert de Niro',
          'Andy gracia', 'Gary Oldman', 'Al Pacino', 'Al Pacino'),
      Question('How Much Did Joey Accidentally Buy The Sailboat For?', '15,000',
          '20,000', '25,000', '30,000 ', '20,000'),
      Question(
          'What Is The Name Of The Woman Ross Slept With When He Thought He Was On A Break?',
          'Chloe',
          'Jessica',
          'Meghan',
          'Carla',
          'Chloe'),
      Question('What Is Chandler\'s Middle Name?', 'Gabriel', "Toby", "Muriel",
          'Doris', 'Muriel'),
      Question('What is Joey and Chandler\s code word for danger?', 'Unagi',
          'Kaw Kaw', 'Bert', 'Danger', 'Bert'),
      Question(
          'What does Chandler\'s co-worker, Bob, think Chandler\'s name is?',
          'Daniel',
          'Chanandler',
          'Toby',
          'Micheal',
          'Toby'),
      Question(
          'What was the reason of fire at Phoebe\'s and Rachel\'s apartment',
          'Curling iron',
          'Scented candles',
          'Flat iron',
          'Grease on stove',
          'Flat iron')
    ],
  },
  'astronomy': {
    'questions': <Question>[
      Question(
          'Hydrogen bomb is based on the principle of ',
          'Nuclear Fission',
          'Natural Radioactivity',
          'Nuclear Fusion',
          'Artificial Radioactivity',
          'Nuclear Fusion'),
      Question(
          'The device employed to measure the diameters of stars and our galaxy (Milky Way) is called:',
          'Photometer',
          'Barometer',
          'Viscometer',
          'Interferometer',
          'Interferometer'),
      Question('What is the densest object in Universe', 'Black Hole', 'Quasar',
          'Neutron Star', 'Wormhole', 'Neutron Star'),
      Question('Who invented telescope', 'Hans Lippershey', 'Johannes Kepler',
          'Galileo', 'Archimedes', 'Hans Lippershey'),
      Question(
          'Which type of electromagnetic energy has the largest wavelength',
          'Infrared',
          'Ultraviolet',
          'X-ray',
          'Radiowave',
          'Radiowave'),
      Question('Stars like Earth\'s sun most likely formed directly from a?',
          'Nebula', 'Red Giant', 'Supernova', 'White Dwarf', 'Nebula'),
      Question('Which object in the solar Sytem has the greast density',
          'Jupiter', 'Earth', 'Sun', 'Saturn', 'Earth'),
      Question('Which planet\'s orbit around the Sun is nearly circular',
          'Earth', 'Mars', 'Jupiter', 'Venus', 'Venus'),
      Question(
          'Which process produces the energy that allows the star to radiate visible light',
          'Nuclear fusion',
          'Nuclear fission',
          'Insolation',
          'Radioactive decay',
          'Nuclear fusion'),
      Question('Which color indicates the hottest star surface tenperature',
          'Red', 'Blue', 'White', 'Yellow', 'White')
    ],
  },
  'tech': {
    'questions': <Question>[
      Question('Ctrl, Shift and Alt are called .......... keys.', 'adjustment',
          'modifier', 'function', 'alphanumeric', 'modifier'),
      Question(
          'A computer cannot "boot" if it does not have the',
          'Operating System',
          'Compiler',
          'Loader',
          'Assembler',
          'Operating System'),
      Question(
          'Who developed yahoo',
          'Dennis Ritchie & Ken Thompson',
          'David Filo & Jerry Yang',
          'Vint Cerf & Robert Kahn',
          'Steve Case & Jeff Bezos',
          'David Filo & Jerry Yang'),
      Question('Which is the first search engine on internet', 'Google',
          'Altavista', 'Archie', 'WAIS', 'Archie'),
      Question('In computer world, trojan is referred to', 'Virus', 'Worm',
          'Malware', 'Spyware', 'Malware'),
      Question('A folder in windows computer can\'t be saved with name', 'con',
          'mac', 'mak', 'can', 'con'),
      Question(
          'Which key combination is used to permanently delete a file or folder',
          'Alt+Delete',
          'Shift+Delete',
          'Ctrl+Delete',
          'Delete',
          'Shift+Delete'),
      Question('Microsoft Office\'s personal information manager is', 'Access',
          'Internet Explorer', 'Organizer', 'Outlook', 'Outlook'),
      Question('What is the limit of characters of a tweet on Twitter', '260',
          '270', '280', '290', '280'),
      Question(
          'Which company first introduced the Emojis internationally on their mobile phones',
          'SamSung',
          'BlackBerry',
          'Nokia',
          'Apple',
          'Apple')
    ],
  },
  'mcu': {
    'questions': <Question>[
      Question(
          'In the films, what does S.H.I.E.L.D. stand for?',
          'Strategic Hazard Intervention Espionage Logistics Directorate',
          'Strategic Homeland Intervention, Enforcement and Logistics Division',
          'Supreme Headquarters, International Espionage, Law-Enforcement Division',
          'Superheroes Help In Enabling Localised Defence',
          'Strategic Homeland Intervention, Enforcement and Logistics Division'),
      Question('What\'s Agent Coulson\'s first name?', 'Paul', 'Chris', 'Phil',
          'Avan', 'Phil'),
      Question(
          'After which \'80s TV star did Star-Lord name his ship?',
          'Chritina AppleGate',
          'Heather Locklear',
          'Tiffani Thiessan',
          'Alyssa Milano',
          'Alyssa Milano'),
      Question(
          'In the comics, who created Captain America\’s shield?',
          'Dr. Terrible',
          'Howard Stark',
          'David Myers',
          'Dr. Myron MacLain',
          'Dr. Myron MacLain'),
      Question(
          'Name this alien race that appeared in \'Captain Marvel\'.',
          'The Sakaarans',
          'The Kree',
          'The Xandarians',
          'The Chitauri',
          'The Kree'),
      Question(
          'In \'The Avengers\', what S.H.I.E.L.D. agent does Black Widow say first brought her into the fold?',
          'Hawkeye',
          'Nick Fury',
          'Agent Coulson',
          'Steve Rogers',
          'Hawkeye'),
      Question(
          'The Fantastic Four have the headquarters in what building?',
          'Stark Tower',
          'Xavier Institute',
          'Fantastic Headquaters',
          'Baxter Building',
          'Baxter Building'),
      Question(
          'What did Peggy Carter promise to Steve Rogers (Captain America) before he crashed Red Skull\'s bomber?',
          'A date',
          'A fondue',
          'A Dance',
          'A Kiss',
          'A Dance'),
      Question(
          'What\'s the final movie in Marvel\'s Phase 1?',
          'Iron Man 3',
          'Avengers Endgame',
          'The Avengers',
          'Guardians of Galaxy',
          'The Avengers'),
      Question(
          'Deadpool joined the Weapon X program because',
          'He had incurable cancer',
          'He wanted to fight for justice',
          'He was forced to',
          'He thought it would be fun',
          'He had incurable cancer')
    ]
  }
};
